server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/minibms
spring.datasource.username=minibms
spring.datasource.password=minibms

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

mqtt.host=tcp://localhost:1883
mqtt.clientId=minibms-backend-${random.uuid}
mqtt.topicTelemetry=miniBMS/room1/telemetry
mqtt.topicConfig=miniBMS/room1/config
mqtt.topicCmd=miniBMS/room1/cmd